export const hotels = [
	{
		
		imgUrl: "https://i.ibb.co/KXX7Wmn/travel-img-1.png",
		title: "Light bright airy stylish apt & safe peaceful stay",
		guests: 4,
		bedrooms: 2,
		beds: 2,
		baths: 2,
		info1: "Wif Air conditioning Kitchen",
		info2: "Cancellation fexibility availiable",
		ratings: 4.9,
		totalRating: 20,
		price: 34,
		cords: { lat: 21.4171963, lng: 91.977232 },
	},
	{
		
		imgUrl: "https://i.ibb.co/w7NjLP1/travel-img-2.png",
		title: "Apartment in Lost Panorama",
		guests: 4,
		bedrooms: 2,
		beds: 2,
		baths: 2,
		info1: "Wif Air conditioning Kitchen",
		info2: "Cancellation fexibility availiable",
		ratings: 4.8,
		totalRating: 10,
		price: 52,
		cords: { lat: 21.4172171, lng: 91.9772095 },
	},
	{
		
		imgUrl: "https://i.ibb.co/wYMBf0w/travel-img-3.png",
		title: "AR Lounge & Pool (r&r + b&b)",
		guests: 4,
		bedrooms: 2,
		beds: 2,
		baths: 2,
		info1: "Wif Air conditioning Kitchen",
		info2: "Cancellation fexibility availiable",
		ratings: 4.9,
		totalRating: 25,
		price: 44,
		cords: { lat: 21.4172171, lng: 91.9772095 },
	},
];
